import React, { useEffect, useMemo, useState } from "react";
import { Card, Button, Form, Row, Col, Table, Spinner, Alert, Badge, Accordion } from "react-bootstrap";
import { BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import { BarChart3 } from 'lucide-react';
import AsyncAlumnoSelect from "../Components/Controls/AsyncAlumnoSelect";
import { useAuth } from "../Context/AuthContext";
import { useLocation } from "react-router-dom";
import { listarAlumnosConFiltros, listarAlumnosEgresados } from "../Services/AlumnoService";
import { listarCursos, listarCursosPorDocente, listarCursosPorPreceptor } from "../Services/CursoService";
import { listarCalifPorAnio } from "../Services/CalificacionesService";
import { obtenerNotaFinalSimple } from "../Services/NotaFinalService";
import { resumenNotasAlumnoPorAnio } from "../Services/ReporteNotasService";
import { listarHistorialAlumnoFiltrado } from "../Services/HistorialCursoService";
import { getTituloCurso } from "../utils/cursos";
import Breadcrumbs from "../Components/Botones/Breadcrumbs";
import BackButton from "../Components/Botones/BackButton";
import Estadisticas from "../Components/Reportes/Estadisticas";
import { useCicloLectivo } from "../Context/CicloLectivoContext";

// Contract expected from backend (approx):
// Contrato backend confirmado:
// CalificacionesAlumnoAnioResponse { code, mensaje, calificacionesAlumnoResumenDto }
// calificacionesAlumnoResumenDto: { alumnoId, dni, apellido, nombre, anio, materias: CalificacionesMateriaResumenDto[] }
// CalificacionesMateriaResumenDto: { materiaId, materiaNombre, e1Notas: int[], e2Notas: int[], e1: number, e2: number, pg: number, estado: string }

export default function ReporteNotasAlumnos() {
  const { user } = useAuth();
  const token = user?.token;
  const location = useLocation();
  
  // Leer parámetros desde state o desde URL query params
  const params = new URLSearchParams(location.search);
  const preselectedAlumnoId = location.state?.preselectedAlumnoId || params.get('alumnoId');
  const autoGenerate = location.state?.autoGenerate || params.get('autoGenerate') === 'true';
  const anioFromUrl = params.get('anio');

  const [anio, setAnio] = useState(anioFromUrl ? Number(anioFromUrl) : new Date().getFullYear());
  const [alumnoId, setAlumnoId] = useState(preselectedAlumnoId || "");
  const [alumnoOption, setAlumnoOption] = useState(null);
  const [alumnos, setAlumnos] = useState([]);
  const [incluirEgresados, setIncluirEgresados] = useState(false);
  const [anioEgreso, setAnioEgreso] = useState(new Date().getFullYear());
  const [cursos, setCursos] = useState([]);
  const [cursoAnioSel, setCursoAnioSel] = useState("");
  const [divisionSel, setDivisionSel] = useState("");
  const [cursoId, setCursoId] = useState("");
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const { cicloLectivo } = useCicloLectivo();

  // (Reemplazado por componente AsyncAlumnoSelect)

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [data, setData] = useState(null);
  const [diag, setDiag] = useState(null); // info de diagnóstico
  // const [rawForYear, setRawForYear] = useState(null); // calificaciones crudas del año
  const printRef = React.useRef(null);
  // PFA (Promedio Final Anual) por materia (clave: materiaId -> PFA)
  const [nfMap, setNfMap] = useState({});
  // Remontar selector cuando cambian filtros (año/división) para forzar recarga
  const alumnoSelectKey = React.useMemo(
    () => `alumno-${cursoAnioSel || 'any'}-${divisionSel || 'any'}-${cursoId || 'none'}`,
    [cursoAnioSel, divisionSel, cursoId]
  );

  // Cargar cursos (según rol)
  useEffect(() => {
    let active = true;
    async function loadCursos() {
      try {
        let lista = [];
        if (user?.rol === "ROLE_DOCENTE" && user?.docenteId) {
          lista = await listarCursosPorDocente(token, user.docenteId);
        } else if (user?.rol === "ROLE_PRECEPTOR" && user?.preceptorId) {
          lista = await listarCursosPorPreceptor(token, user.preceptorId);
        } else {
          lista = await listarCursos(token);
        }
        if (active) setCursos(lista || []);
      } catch {
        // noop
      }
    }
    if (token) loadCursos();
    return () => { active = false; };
  }, [token, user]);

  // Generar años posibles para egresados
  const aniosEgresoDisponibles = useMemo(() => {
    const currentYear = new Date().getFullYear();
    const years = [];
    for (let i = currentYear + 1; i >= currentYear - 10; i--) {
      years.push(i);
    }
    return years;
  }, []);

  // Cargar alumnos según filtro de egresados
  useEffect(() => {
    let active = true;
    async function load() {
      try {
        let lista = [];
        if (incluirEgresados) {
          const listaEgresados = await listarAlumnosEgresados(token);
          lista = (listaEgresados || []).filter(alumno => {
            if (!alumno.historialCursos || alumno.historialCursos.length === 0) return false;
            const historiales = [...alumno.historialCursos]
              .filter(h => h.fechaHasta != null)
              .sort((a, b) => new Date(b.fechaHasta) - new Date(a.fechaHasta));
            if (historiales.length === 0) return false;
            const ultimoHistorial = historiales[0];
            const yearEgreso = new Date(ultimoHistorial.fechaHasta).getFullYear();
            return yearEgreso === anioEgreso;
          });
        } else {
          const listaActivos = await listarAlumnosConFiltros(token, {});
          // Filtrar alumnos que tengan historial en el año seleccionado
          lista = (listaActivos || []).filter(alumno => {
            if (!alumno.historialCursos || alumno.historialCursos.length === 0) return false;
            return alumno.historialCursos.some(h => {
              if (!h.fechaDesde) return false;
              const yearHistorial = new Date(h.fechaDesde).getFullYear();
              return yearHistorial === Number(anio);
            });
          });
        }
        if (active) setAlumnos(lista);
      } catch (e) {
        console.error(e);
      }
    }
    if (token) load();
    return () => { active = false; };
  }, [token, incluirEgresados, anioEgreso, anio]);

  // Derivar opciones de año y división a partir de cursos
  const aniosCursoOptions = useMemo(() => {
    const set = new Set();
    (cursos || []).forEach(c => { if (c.anio != null) set.add(String(c.anio)); });
    return Array.from(set).sort((a,b)=> Number(a)-Number(b));
  }, [cursos]);

  const divisionesOptions = useMemo(() => {
    if (!cursoAnioSel) return [];
    const set = new Set();
    (cursos || []).filter(c => String(c.anio) === String(cursoAnioSel)).forEach(c => {
      if (c.division != null && c.division !== '') set.add(String(c.division));
    });
    return Array.from(set).sort();
  }, [cursos, cursoAnioSel]);

  // Cuando cambian año y división, calcular cursoId
  useEffect(() => {
    const match = (cursos || []).find(c => String(c.anio) === String(cursoAnioSel) && String(c.division) === String(divisionSel));
    setCursoId(match?.id ? String(match.id) : "");
  }, [cursos, cursoAnioSel, divisionSel]);

  // Al cambiar curso, limpiar alumno seleccionado (salvo que venga preseleccionado)
  useEffect(() => {
    if (!preselectedAlumnoId) {
      setAlumnoOption(null);
      setAlumnoId("");
    }
  }, [cursoId, preselectedAlumnoId]);

  // Cargar alumno preseleccionado si viene del state
  useEffect(() => {
    if (!preselectedAlumnoId || !token) return;
    let active = true;
    async function loadPreselected() {
      try {
        const lista = await listarAlumnosConFiltros(token, {});
        const alumno = (lista || []).find(a => String(a.id) === String(preselectedAlumnoId));
        if (active && alumno) {
          const opt = {
            value: alumno.id,
            label: `${alumno.apellido || ''}, ${alumno.nombre || ''}${alumno.dni ? ' - ' + alumno.dni : ''}`.trim()
          };
          setAlumnoOption(opt);
          setAlumnoId(String(alumno.id));
        }
      } catch (e) {
        console.error("Error cargando alumno preseleccionado:", e);
      }
    }
    loadPreselected();
    return () => { active = false; };
  }, [preselectedAlumnoId, token]);

  // Auto-generar reporte si viene autoGenerate=true o si viene alumnoId por URL
  useEffect(() => {
    if ((autoGenerate || preselectedAlumnoId) && alumnoId && anio && !hasAutoGenerated && !loading) {
      setHasAutoGenerated(true);
      // Simular click en el botón después de un pequeño delay
      setTimeout(() => {
        const submitBtn = document.querySelector('button[type="submit"]');
        submitBtn?.click();
      }, 500);
    }
  }, [autoGenerate, preselectedAlumnoId, alumnoId, anio, hasAutoGenerated, loading]);

  // Helpers para búsqueda
  // (buscador encapsulado en componente)

  // Alumno options handled by AsyncAlumnoSelect

  const aniosPosibles = useMemo(() => {
    const y = new Date().getFullYear();
    return [y - 2, y - 1, y, y + 1];
  }, []);

  const onSubmit = async (e) => {
    e.preventDefault();
    setError("");
    setData(null);
    setNfMap({});
    if (!alumnoId) {
      setError("Seleccioná un alumno");
      return;
    }
    if (!anio) {
      setError("Seleccioná un año");
      return;
    }
    try {
      setLoading(true);
      setDiag(null);
      const res = await resumenNotasAlumnoPorAnio(token, alumnoId, anio);
      setData(res);
      if (res?.code && res.code < 0) setError(res.mensaje || "Error en el reporte");

      // Cargar Nota Final por materia en paralelo (si hay materias)
      try {
        const materias = res?.calificacionesAlumnoResumenDto?.materias || [];
        const ids = materias.map(m => m.materiaId).filter(id => id != null);
        if (ids.length) {
          const pool = 6;
          const resultados = {};
          let i = 0;
          async function worker() {
            while (i < ids.length) {
              const idx = i++;
              const mid = ids[idx];
              try {
                const resp = await obtenerNotaFinalSimple(token, Number(alumnoId), Number(mid), Number(anio));
                // El endpoint simple puede devolver { notaFinal: number } o un número directo según backend
                const val = typeof resp === 'number' ? resp : (resp?.notaFinal ?? resp?.valor ?? null);
                resultados[mid] = val;
              } catch {
                resultados[mid] = null;
              }
            }
          }
          const workers = Array.from({ length: Math.min(pool, ids.length) }, () => worker());
          await Promise.all(workers);
          setNfMap(resultados);
        }
      } catch {
        // noop NF
      } finally {
        // done
      }

      // Traigo también las calificaciones crudas del año para diagnóstico y posibles tooltips de fechas
      try {
        const crudas = await listarCalifPorAnio(token, alumnoId, anio);
        const count = Array.isArray(crudas?.calificaciones) ? crudas.calificaciones.length : 0;
        const materiasLen = (res?.calificacionesAlumnoResumenDto?.materias || []).length;
        if (!error && materiasLen === 0) {
          if (count > 0) {
            setDiag({ type: "warn", msg: `Se encontraron ${count} calificaciones en ${anio}, pero no se pudieron agrupar (¿números de nota 1-4 y etapas 1-2?).` });
          } else {
            setDiag({ type: "info", msg: `No se encontraron calificaciones con fecha del año ${anio} para este alumno. Verificá la fecha de las notas.` });
          }
        }
      } catch {
        // ignorar
      }
    } catch (err) {
      setError(err.message || "Error al generar reporte");
    } finally {
      setLoading(false);
    }
  };

  // Buscar por DNI: setea un override de lista para el selector y autoselecciona si hay un único resultado
  // DNI search now handled inside AsyncAlumnoSelect

  const resumenDto = data?.calificacionesAlumnoResumenDto;
  const resumen = useMemo(() => resumenDto?.materias || [], [resumenDto]);

  const exportCSV = () => {
    if (!resumen || resumen.length === 0) return;
    const header = [
      "Materia",
      "E1 N1","E1 N2","E1 N3","E1 N4","E1 Prom",
      "E2 N1","E2 N2","E2 N3","E2 N4","E2 Prom",
      "PG","CO","EX","PFA","Estado"
    ];
    const rows = resumen.map(r => {
      const e1arr = Array.isArray(r.e1Notas) ? r.e1Notas : [];
      const e2arr = Array.isArray(r.e2Notas) ? r.e2Notas : [];
      return [
        r.materiaNombre || "",
        e1arr[0] ?? "", e1arr[1] ?? "", e1arr[2] ?? "", e1arr[3] ?? "", (r.e1 ?? ""),
        e2arr[0] ?? "", e2arr[1] ?? "", e2arr[2] ?? "", e2arr[3] ?? "", (r.e2 ?? ""),
        (r.pg ?? ""), (r.co ?? ""), (r.ex ?? ""), (nfMap?.[r.materiaId] ?? ""), (r.estado ?? "")
      ];
    });
    const csv = [header, ...rows]
      .map(cols => cols.map(v => {
        const s = v == null ? "" : String(v);
        // escapar comillas y envolver si hay separadores
        const escaped = '"' + s.replace(/"/g, '""') + '"';
        return escaped;
      }).join(","))
      .join("\n");
    const blob = new Blob(["\uFEFF" + csv], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    const nombreAlumno = resumenDto ? `${resumenDto.apellido || ''}_${resumenDto.nombre || ''}`.trim() : "alumno";
    a.href = url;
    a.download = `reporte_notas_${nombreAlumno}_${anio}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Stats globales
  const pgList = resumen.map(r => r.pg).filter(v => typeof v === 'number');
  const totalMaterias = resumen.length;
  const aprobadas = resumen.filter(r => (r.estado || '').toLowerCase() === 'aprobado' || (r.pg ?? 0) >= 6).length;
  const desaprobadas = totalMaterias - aprobadas;
  const promedioGeneralAlumno = pgList.length ? Math.round((pgList.reduce((a,b)=>a+b,0)/pgList.length)*10)/10 : null;

  // KPIs y gráficos
  const kpisData = useMemo(() => {
    if (!resumen || resumen.length === 0) return null;

    // Promedios E1 y E2
    const e1List = resumen.map(r => r.e1).filter(v => typeof v === 'number');
    const e2List = resumen.map(r => r.e2).filter(v => typeof v === 'number');
    const promedioE1 = e1List.length ? (e1List.reduce((a,b)=>a+b,0)/e1List.length).toFixed(1) : null;
    const promedioE2 = e2List.length ? (e2List.reduce((a,b)=>a+b,0)/e2List.length).toFixed(1) : null;

    // Mejor y peor materia
    const conPG = resumen.filter(r => typeof r.pg === 'number').sort((a,b) => b.pg - a.pg);
    const mejorMateria = conPG[0] ? { nombre: conPG[0].materiaNombre?.substring(0, 30), pg: conPG[0].pg } : null;
    const peorMateria = conPG[conPG.length - 1] ? { nombre: conPG[conPG.length - 1].materiaNombre?.substring(0, 30), pg: conPG[conPG.length - 1].pg } : null;

    // Desviación estándar
    let desviacion = null;
    if (pgList.length > 1 && promedioGeneralAlumno != null) {
      const varianza = pgList.reduce((acc, pg) => acc + Math.pow(pg - promedioGeneralAlumno, 2), 0) / pgList.length;
      desviacion = Math.sqrt(varianza).toFixed(2);
    }

    // Distribución por rangos de notas
    const distribucion = [
      { rango: '0-3', count: 0, color: '#dc3545' },
      { rango: '4-5', count: 0, color: '#fd7e14' },
      { rango: '6-7', count: 0, color: '#ffc107' },
      { rango: '8-10', count: 0, color: '#28a745' }
    ];
    pgList.forEach(pg => {
      if (pg >= 0 && pg <= 3) distribucion[0].count++;
      else if (pg >= 4 && pg <= 5) distribucion[1].count++;
      else if (pg >= 6 && pg <= 7) distribucion[2].count++;
      else if (pg >= 8 && pg <= 10) distribucion[3].count++;
    });

    // Datos para radar chart (top 10 materias por nombre corto)
    const radarData = resumen
      .filter(r => typeof r.pg === 'number')
      .slice(0, 10)
      .map(r => ({
        materia: r.materiaNombre?.substring(0, 15) || 'Sin nombre',
        pg: r.pg
      }));

    // Datos para comparación E1 vs E2 por materia (top 10)
    const comparacionData = resumen
      .filter(r => typeof r.e1 === 'number' || typeof r.e2 === 'number')
      .slice(0, 10)
      .map(r => ({
        materia: r.materiaNombre?.substring(0, 20) || 'Sin nombre',
        e1: r.e1 ?? 0,
        e2: r.e2 ?? 0
      }));

    // Datos para evolución de notas (promedio de todas las N1, N2, N3, N4)
    const evolucionE1 = { n1: 0, n2: 0, n3: 0, n4: 0, count: 0 };
    const evolucionE2 = { n1: 0, n2: 0, n3: 0, n4: 0, count: 0 };
    resumen.forEach(r => {
      if (Array.isArray(r.e1Notas)) {
        r.e1Notas.forEach((nota, idx) => {
          if (typeof nota === 'number') {
            if (idx === 0) evolucionE1.n1 += nota;
            else if (idx === 1) evolucionE1.n2 += nota;
            else if (idx === 2) evolucionE1.n3 += nota;
            else if (idx === 3) evolucionE1.n4 += nota;
          }
        });
        if (r.e1Notas.some(n => typeof n === 'number')) evolucionE1.count++;
      }
      if (Array.isArray(r.e2Notas)) {
        r.e2Notas.forEach((nota, idx) => {
          if (typeof nota === 'number') {
            if (idx === 0) evolucionE2.n1 += nota;
            else if (idx === 1) evolucionE2.n2 += nota;
            else if (idx === 2) evolucionE2.n3 += nota;
            else if (idx === 3) evolucionE2.n4 += nota;
          }
        });
        if (r.e2Notas.some(n => typeof n === 'number')) evolucionE2.count++;
      }
    });

    const evolucionData = [
      { nota: 'N1', e1: evolucionE1.count ? (evolucionE1.n1 / evolucionE1.count).toFixed(1) : 0, e2: evolucionE2.count ? (evolucionE2.n1 / evolucionE2.count).toFixed(1) : 0 },
      { nota: 'N2', e1: evolucionE1.count ? (evolucionE1.n2 / evolucionE1.count).toFixed(1) : 0, e2: evolucionE2.count ? (evolucionE2.n2 / evolucionE2.count).toFixed(1) : 0 },
      { nota: 'N3', e1: evolucionE1.count ? (evolucionE1.n3 / evolucionE1.count).toFixed(1) : 0, e2: evolucionE2.count ? (evolucionE2.n3 / evolucionE2.count).toFixed(1) : 0 },
      { nota: 'N4', e1: evolucionE1.count ? (evolucionE1.n4 / evolucionE1.count).toFixed(1) : 0, e2: evolucionE2.count ? (evolucionE2.n4 / evolucionE2.count).toFixed(1) : 0 }
    ];

    return {
      promedioE1,
      promedioE2,
      mejorMateria,
      peorMateria,
      desviacion,
      distribucion,
      radarData,
      comparacionData,
      evolucionData
    };
  }, [resumen, pgList, promedioGeneralAlumno]);

  const printOnlyTable = () => {
    if (!printRef.current) return;
    const win = window.open('', '_blank');
    if (!win) return;
    const css = `
      body { font-family: Arial, sans-serif; padding: 16px; }
      h3 { margin: 0 0 12px 0; }
      .kpi-section { margin: 0 0 16px 0; padding: 12px; border: 1px solid #ddd; background: #f9f9f9; }
      .kpi-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; }
      .kpi-card { padding: 8px; border: 1px solid #ccc; background: #fff; }
      .kpi-label { font-size: 11px; font-weight: 600; color: #555; margin-bottom: 4px; }
      .kpi-value { font-size: 18px; font-weight: bold; }
      table { width: 100%; border-collapse: collapse; }
      th, td { border: 1px solid #333; padding: 6px 8px; font-size: 12px; }
      thead tr:first-child th { background: #f0f0f0; }
    `;
    win.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Reporte de Notas</title><style>${css}</style></head><body>`);
    win.document.write(`<h3>Notas de ${resumenDto?.apellido || ''}, ${resumenDto?.nombre || ''} - Año ${resumenDto?.anio || anio}</h3>`);
    
    // KPIs en PDF
    if (kpisData) {
      win.document.write(`<div class="kpi-section">`);
      win.document.write(`<div class="kpi-grid">`);
      win.document.write(`<div class="kpi-card"><div class="kpi-label">Promedio E1</div><div class="kpi-value">${kpisData.promedioE1 ?? '-'}</div></div>`);
      win.document.write(`<div class="kpi-card"><div class="kpi-label">Promedio E2</div><div class="kpi-value">${kpisData.promedioE2 ?? '-'}</div></div>`);
      win.document.write(`<div class="kpi-card"><div class="kpi-label">Mejor Materia</div><div class="kpi-value">${kpisData.mejorMateria?.pg ?? '-'}</div><div style="font-size:10px;color:#666;">${kpisData.mejorMateria?.nombre || '-'}</div></div>`);
      win.document.write(`<div class="kpi-card"><div class="kpi-label">Consistencia</div><div class="kpi-value">${kpisData.desviacion ?? '-'}</div><div style="font-size:10px;color:#666;">Desv. estándar</div></div>`);
      win.document.write(`</div></div>`);
    }
    
    win.document.write(printRef.current.innerHTML);
    win.document.write('</body></html>');
    win.document.close();
    win.focus();
    setTimeout(() => { win.print(); win.close(); }, 300);
  };

  const [cursoActual, setCursoActual] = useState(null);

  // Buscar el curso real del alumno para el año seleccionado
  useEffect(() => {
    async function fetchCursoActual() {
      setCursoActual(null);
      if (!alumnoId || !anio || !cicloLectivo?.id) return;
      try {
        const hist = await listarHistorialAlumnoFiltrado(token, alumnoId, { cicloLectivoId: cicloLectivo.id });
        if (Array.isArray(hist?.historialCursos)) {
          // Buscar el historial del año seleccionado
          const h = hist.historialCursos.find(hc => {
            const fechaDesde = hc.fechaDesde ? new Date(hc.fechaDesde).getFullYear() : null;
            return fechaDesde === Number(anio);
          });
          setCursoActual(h?.curso || null);
        }
      } catch {
        setCursoActual(null);
      }
    }
    fetchCursoActual();
  }, [alumnoId, anio, cicloLectivo?.id, token]);

  return (
    <div className="container mt-4">
      <div className="mb-1"><Breadcrumbs /></div>
      <div className="mb-2"><BackButton /></div>
      <h2 className="mb-2">Notas de un Alumno</h2>
      <p className="text-muted mb-3">
        Consultá el detalle completo de calificaciones por materia, incluyendo las notas de cada etapa, promedios y estado de aprobación.
      </p>

      <Card className="mb-4">
        <Card.Body>
          <Form onSubmit={onSubmit}>
            <Row className="g-3">
              {!incluirEgresados && (
                <>
                  <Col md={2}>
                    <Form.Label>Curso (Año, opcional)</Form.Label>
                    <Form.Select value={cursoAnioSel} onChange={(e)=>setCursoAnioSel(e.target.value)}>
                      <option value="">Todos</option>
                      {aniosCursoOptions.map(an => (
                        <option key={an} value={an}>{an}</option>
                      ))}
                    </Form.Select>
                  </Col>
                  <Col md={2}>
                    <Form.Label>División (opcional)</Form.Label>
                    <Form.Select value={divisionSel} onChange={(e)=>setDivisionSel(e.target.value)} disabled={!cursoAnioSel}>
                      <option value="">Todas</option>
                      {divisionesOptions.map(d => (
                        <option key={d} value={d}>{d}</option>
                      ))}
                    </Form.Select>
                  </Col>
                </>
              )}
              <Col md={2}>
                <Form.Label>Año</Form.Label>
                <Form.Select value={anio} onChange={(e) => setAnio(e.target.value)}>
                  {aniosPosibles.map((y) => (
                    <option key={y} value={y}>
                      {y}
                    </option>
                  ))}
                </Form.Select>
              </Col>
              <Col md={incluirEgresados ? 6 : 4}>
                <Form.Label>Alumno</Form.Label>
                <AsyncAlumnoSelect
                  key={alumnoSelectKey}
                  token={token}
                  value={alumnoOption}
                  onChange={(opt) => { setAlumnoOption(opt); setAlumnoId(opt?.value || ""); }}
                  cursoAnio={incluirEgresados ? "" : cursoAnioSel}
                  cursoDivision={incluirEgresados ? "" : divisionSel}
                  cursoId={incluirEgresados ? "" : cursoId}
                  alumnosExternos={incluirEgresados ? alumnos : null}
                />
              </Col>
              <Col md={2} className="d-flex align-items-end gap-2">
                <Button type="submit" variant="primary" disabled={loading || !alumnoId} className="flex-grow-1">
                  {loading ? (
                    <>
                      <Spinner size="sm" animation="border" className="me-2" /> Generando...
                    </>
                  ) : (
                    "Generar reporte"
                  )}
                </Button>
                {!incluirEgresados && (cursoAnioSel || divisionSel || alumnoOption) && (
                  <Button 
                    variant="outline-secondary" 
                    size="sm"
                    onClick={() => {
                      setCursoAnioSel("");
                      setDivisionSel("");
                      setAlumnoOption(null);
                      setAlumnoId("");
                    }}
                    title="Limpiar filtros"
                  >
                    Limpiar
                  </Button>
                )}
              </Col>
            </Row>
            <Row className="g-3 mt-2">
              <Col md={12}>
                <Form.Check 
                  type="checkbox"
                  label="Buscar egresados"
                  checked={incluirEgresados}
                  onChange={(e) => { 
                    setIncluirEgresados(e.target.checked);
                    if (!e.target.checked) {
                      setAlumnoOption(null);
                      setAlumnoId("");
                    }
                  }}
                  className="d-inline-block me-3"
                />
                {incluirEgresados && (
                  <>
                    <Form.Label className="small d-inline-block me-2 mb-0">Año de egreso:</Form.Label>
                    <Form.Select 
                      size="sm"
                      value={anioEgreso} 
                      onChange={(e)=>setAnioEgreso(Number(e.target.value))}
                      className="d-inline-block"
                      style={{ width: 'auto' }}
                    >
                      {aniosEgresoDisponibles.map(y => (
                        <option key={y} value={y}>{y}</option>
                      ))}
                    </Form.Select>
                  </>
                )}
              </Col>
            </Row>
          </Form>
        </Card.Body>
      </Card>

      {error && <Alert variant="danger">{error}</Alert>}
      {!error && diag && (
        <Alert variant={diag.type === 'warn' ? 'warning' : 'info'}>{diag.msg}</Alert>
      )}

      {loading && (
        <div className="d-flex align-items-center">
          <Spinner animation="border" className="me-2" /> Cargando datos...
        </div>
      )}

      {!loading && data && !error && (
        <>
          {/* Acordeón con KPIs y Gráficos */}
          {kpisData && (
            <Accordion className="mb-3 d-print-none">
              <Accordion.Item eventKey="0">
                <Accordion.Header>
                  <BarChart3 size={20} className="me-2" />
                  <strong>KPIs y Gráficos - Análisis de Rendimiento</strong>
                </Accordion.Header>
                <Accordion.Body>
                  <Row className="g-3 mb-3">
                    <Col sm={12} md={6} lg={3}>
                      <Card className="h-100 border-primary">
                        <Card.Body>
                          <div className="text-primary mb-1" style={{ fontSize: '0.85rem', fontWeight: 600 }}>Promedio E1</div>
                          <div style={{ fontSize: '1.5rem', fontWeight: 'bold' }}>{kpisData.promedioE1 ?? '-'}</div>
                        </Card.Body>
                      </Card>
                    </Col>
                    <Col sm={12} md={6} lg={3}>
                      <Card className="h-100 border-info">
                        <Card.Body>
                          <div className="text-info mb-1" style={{ fontSize: '0.85rem', fontWeight: 600 }}>Promedio E2</div>
                          <div style={{ fontSize: '1.5rem', fontWeight: 'bold' }}>{kpisData.promedioE2 ?? '-'}</div>
                        </Card.Body>
                      </Card>
                    </Col>
                    <Col sm={12} md={6} lg={3}>
                      <Card className="h-100 border-success">
                        <Card.Body>
                          <div className="text-success mb-1" style={{ fontSize: '0.85rem', fontWeight: 600 }}>Mejor Materia</div>
                          <div style={{ fontSize: '1.2rem', fontWeight: 'bold' }}>{kpisData.mejorMateria?.pg ?? '-'}</div>
                          <div className="text-muted" style={{ fontSize: '0.75rem' }}>{kpisData.mejorMateria?.nombre || '-'}</div>
                        </Card.Body>
                      </Card>
                    </Col>

                  </Row>


                </Accordion.Body>
              </Accordion.Item>
            </Accordion>
          )}

          {/* Estadísticas rápidas */}
          <Card className="mb-3 d-print-none">
            <Card.Body>
              <Estadisticas
                items={[
                  { label: "Materias", value: totalMaterias },
                  { label: "Aprobadas", value: aprobadas, variant: "success" },
                  { label: "Desaprobadas", value: desaprobadas, variant: "danger" },
                  { label: "Promedio General", value: promedioGeneralAlumno ?? "-" },
                ]}
              />
            </Card.Body>
          </Card>

          {/* Tabla detallada con notas por etapa */}
          <Card>
            <Card.Body>
              <div className="d-flex flex-column flex-md-row justify-content-between align-items-md-center mb-3">
                <div>
                  <h5 className="mb-1">Detalle de Notas por Materia</h5>
                  {resumenDto && (
                    <div className="text-muted small">
                      Alumno: {resumenDto.apellido}, {resumenDto.nombre} {resumenDto.dni ? `(DNI ${resumenDto.dni})` : ''}
                      {cursoActual && (
                        <> · Curso: {getTituloCurso(cursoActual)} · Año: {anio}</>
                      )}
                      {!cursoActual && resumenDto.anio && resumenDto.division && (
                        <> · Curso: {resumenDto.anio}°{resumenDto.division} · Año: {anio}</>
                      )}
                      {!cursoActual && resumenDto.anio && !resumenDto.division && (
                        <> · Curso: {resumenDto.anio}° · Año: {anio}</>
                      )}
                    </div>
                  )}
                </div>
                <div className="mt-2 mt-md-0">
                  <Button variant="outline-secondary" size="sm" className="me-2" onClick={exportCSV} disabled={!resumen || resumen.length===0}>
                    Exportar CSV
                  </Button>
                  <Button variant="outline-secondary" size="sm" onClick={printOnlyTable}>
                    Imprimir / PDF (solo tabla)
                  </Button>
                </div>
              </div>

              <div ref={printRef}>
                {Array.isArray(resumen) && resumen.length > 0 ? (
                  <Table striped bordered hover responsive size="sm">
                    <thead>
                      <tr>
                        <th>Materia</th>
                        <th colSpan={5} className="text-center">Calificaciones Etapa 1</th>
                        <th colSpan={5} className="text-center">Calificaciones Etapa 2</th>
                        <th>PG</th>
                        <th>CO</th>
                        <th>EX</th>
                        <th>PFA</th>
                        <th>Estado</th>
                      </tr>
                      <tr>
                        <th></th>
                        <th>N1</th><th>N2</th><th>N3</th><th>N4</th><th>E1</th>
                        <th>N1</th><th>N2</th><th>N3</th><th>N4</th><th>E2</th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      {resumen.map((r, idx) => {
                        const e1 = Array.isArray(r.e1Notas) ? r.e1Notas : [];
                        const e2 = Array.isArray(r.e2Notas) ? r.e2Notas : [];
                        return (
                          <tr key={r.materiaId ?? idx}>
                            <td>{r.materiaNombre}</td>
                            <td>{e1[0] ?? '-'}</td><td>{e1[1] ?? '-'}</td><td>{e1[2] ?? '-'}</td><td>{e1[3] ?? '-'}</td><td><Badge bg="light" text="dark">{r.e1 ?? '-'}</Badge></td>
                            <td>{e2[0] ?? '-'}</td><td>{e2[1] ?? '-'}</td><td>{e2[2] ?? '-'}</td><td>{e2[3] ?? '-'}</td><td><Badge bg="light" text="dark">{r.e2 ?? '-'}</Badge></td>
                            <td><Badge bg={(r.pg ?? 0) >= 6 ? 'success' : 'danger'}>{r.pg ?? '-'}</Badge></td>
                            <td>{r.co ?? '-'}</td>
                            <td>{r.ex ?? '-'}</td>
                            <td>{nfMap?.[r.materiaId] ?? '-'}</td>
                            <td>{r.estado ?? '-'}</td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </Table>
                ) : (
                  <div className="text-muted">Sin datos para mostrar.</div>
                )}
              </div>
            </Card.Body>
          </Card>
        </>
      )}
    </div>
  );
}
